### ISSUE TITLE
Error in MAPE calculation

### ISSUE THREAD

**Issue by nerolite** [mfrasco/Metrics#14]
Hi, I think there might a an error in the calculation of MAPE (mean absolute percentage error).

You have specified the function as:
`$\frac{1}{n} \sum_{i=1}^n \frac{\lvert x_i - y_i \rvert}{x_i}$`
Which results in negative values and positive values which cancel eachother out.

The absolute value calculation should be changed to include the denominator:
`$\frac{1}{n} \sum_{i=1}^n \lvert \frac{ x_i - y_i }{x_i} \rvert$`

https://en.wikipedia.org/wiki/Mean_absolute_percentage_error

**Comment by mfrasco** [comment]
You're absolutely right. Thank you for bringing this to my attention. I will fix this as soon as possible.

**Comment by mfrasco** [comment]
I am closing out this issue. `mape` now takes into account negative values in `actual`. Thanks for bringing this to my attention.

**Comment by nerolite** [comment]
Nice work, appreciate that you fixed it so quickly.
