### ISSUE TITLE
MASE metric

### ISSUE THREAD

**Issue by iblasi** [mfrasco/Metrics#32]
@mfrasco , I am not sure if your MASE metric for time-series is correct.
As you show on the main page ([link](https://github.com/mfrasco/Metrics)), the "m" parameter is the "steps to look back" where "m=1" will be a persistence situtation.
But you are  placing the "n" as dividend an "n-m" as divisor in the formula. However, looking to the original document ([link](http://eva.fcea.edu.uy/pluginfile.php/109034/mod_resource/content/0/2006_Hyndman_Predicc.pdf)) it does not refer a "n" as dividend. So I am not sure if that formula is correct. Can you tell me where did you find the "m-steps to look back" use? I have checked several documents from Hyndman and I did not find nothing about it.

**Comment by mfrasco** [comment]
Hi. Thanks for providing feedback on the package. I just double checked my implementation of MASE, and I couldn't find any irregularities with it. Could you provide a reproducible example that shows that the formula is incorrect?

My source for the definition of MASE comes from his textbook on forecasting. The link is here: https://otexts.org/fpp2/accuracy.html The formula for MASE is under the section titled "scaled errors".

I just checked the algebra and the code that I wrote to arrive at my implementation. However, it's possible that I may have made a mistake. Please let me know if you find a mistake. Thanks so much for your help.

**Comment by mfrasco** [comment]
@iblasi Did you get a chance to see my response?
