### ISSUE TITLE
F1 score issue 

### ISSUE THREAD

**Issue by ashwinimaurya** [mfrasco/Metrics#34]
The code in the packages is:

f1=function (actual, predicted) 
{
    act <- unique(actual)
    pred <- unique(predicted)
    tp <- length(intersect(act, pred))
    fp <- length(setdiff(pred, act))
    fn <- length(setdiff(act, pred))
    if (tp == 0) {
        return(0)
    }
    else {
        precision <- tp/(tp + fp)
        recall <- tp/(tp + fn)
        return(2 * precision * recall/(precision + recall))
    }
}

It should be corrected at line 3-4 etc when computing the act,pred.

**Comment by mfrasco** [comment]
@ashwinimaurya Thanks for opening this issue. `Metrics::f1` is actually defined in the context of information retrieval problems, not binary classification problems. `Metrics::fbeta_score` is probably the metric that you are looking for. Let me know if there is an issue with that function. Also, let me know how to improve the documentation to avoid this issue moving forward.
